# Covid classification from lung X-rays

ներմուծվում են համապատասխան գրադարանները

In [13]:
import os
import numpy as np
import cv2         
import matplotlib.pyplot as plt
import pickle     # модуль сериализации и десериализации объектов в Питоне для последующей их передачи.
import random
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [14]:
shape=(256,256)       #  Քանի որ նկարների չափերը կարող են տարբեր լինել, առաջադրվում է նկարի չափը, բոլոր նկարները հետագայում բերվելու է նույն չափի նոր տրվեն մոդելին
data = []
categories = ['COVID19','NORMAL']




Տրվում է X-Rays նկարների հղումը 

In [15]:
dir ='D:\\Python_ML_Math_2021\\project\\lung_xray\\train'


In [16]:
for category in categories:   # հերթով անցնում է categories-ի էլեմենտների վրայով և ստեղծվում է train.pickle, որը իրենից ներկայացնում է train data-յի բոլոր նկարների pickle դարձրած ֆայլը
    path = os.path.join(dir,category)
    label =  categories.index(category)
    for image in os.listdir(path):
        imgpath = os.path.join(path,image)
        print(imgpath)
        train_img = cv2.imread(imgpath,0)
        train_img=cv2.resize(train_img,shape)
        cv2.imshow('image', train_img)
        train_img = np.array(train_img).flatten()
        data.append([train_img,label])

pick_in = open('train.pickle','wb')
pickle.dump(data,pick_in)
pick_in.close()
pick_in

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1000_bacteria_2931.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1000_virus_1681.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1001_bacteria_2932.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1002_bacteria_2933.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1003_bacteria_2934.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1003_virus_1685.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1004_bacteria_2935.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1004_virus_1686.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1005_bacteria_2936.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1005_virus_1688.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1006_bacteria_2937.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1007_bacteria_29

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1063_bacteria_2997.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1063_virus_1765.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1065_bacteria_2999.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1065_virus_1768.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1066_bacteria_3000.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1066_virus_1769.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1067_bacteria_3001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1067_virus_1770.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1068_bacteria_3002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1068_virus_1771.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1069_bacteria_3003.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1069_virus_1772.jpe

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1115_bacteria_3056.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1115_virus_1840.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1116_virus_1841.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1118_bacteria_3059.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1119_virus_1844.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person111_virus_209.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person111_virus_210.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person111_virus_212.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1120_virus_1845.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1121_virus_1846.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1122_bacteria_3063.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1122_virus_1847.jpeg
D:\Python_ML_

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1165_bacteria_3111.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1165_virus_1959.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1167_bacteria_3113.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1168_bacteria_3114.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1168_bacteria_3115.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1168_virus_1965.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1168_virus_1966.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1169_virus_1968.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person116_virus_221.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1170_bacteria_3117.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1170_virus_1969.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1170_virus_1970.jpeg
D:\

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1217_bacteria_3169.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1217_virus_2063.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1218_bacteria_3171.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1218_virus_2066.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1219_bacteria_3172.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1219_virus_2067.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1220_bacteria_3173.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1220_bacteria_3174.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1220_virus_2068.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1222_bacteria_3177.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1222_virus_2071.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1223_bacteria_3178.

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1266_virus_2158.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1267_bacteria_3226.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1267_virus_2160.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1268_bacteria_3227.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1268_bacteria_3228.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1268_virus_2161.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1269_bacteria_3229.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1269_virus_2162.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person126_virus_255.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1270_bacteria_3230.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1270_virus_2163.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1271_bacteria_3231.jpeg


D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3313.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3314.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3316.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3317.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3318.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_bacteria_3319.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1312_virus_2261.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1313_bacteria_3320.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1313_virus_2264.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1314_virus_2266.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1314_virus_2268.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1314_virus_2269.

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1345_virus_2321.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1346_bacteria_3430.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1346_virus_2322.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1347_virus_2323.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1348_virus_2324.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1348_virus_2326.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1349_bacteria_3434.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1349_bacteria_3436.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1349_bacteria_3437.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1349_bacteria_3438.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1349_bacteria_3439.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person134_virus_268.jpeg


D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1398_bacteria_3548.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1398_virus_2401.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1399_bacteria_3549.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1399_virus_2402.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person139_virus_283.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person13_bacteria_49.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person13_bacteria_50.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1400_bacteria_3550.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1400_bacteria_3551.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1400_bacteria_3553.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1400_bacteria_3554.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1401_bacteria_3555.jpeg

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1438_bacteria_3721.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1438_virus_2452.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1439_bacteria_3722.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1439_virus_2453.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person143_virus_289.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1440_bacteria_3723.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1441_bacteria_3724.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1441_virus_2454.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1441_virus_2457.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1442_bacteria_3726.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1444_bacteria_3732.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1445_bacteria_3734.jp

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1480_bacteria_3858.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1480_bacteria_3859.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1480_virus_2566.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3862.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3863.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3864.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3865.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3866.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3867.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_bacteria_3868.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1481_virus_2567.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1482_bacte

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1512_bacteria_3958.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1512_virus_2631.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1513_bacteria_3962.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1513_virus_2632.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1514_bacteria_3964.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1514_virus_2633.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1516_virus_2643.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1517_bacteria_3968.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1517_virus_2644.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1518_bacteria_3969.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1518_virus_2645.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1519_bacteria_3970.jpe

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1561_bacteria_4077.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1562_bacteria_4078.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1562_bacteria_4081.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1562_bacteria_4087.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1562_bacteria_4089.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1563_bacteria_4092.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1564_bacteria_4094.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1564_virus_2719.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1565_bacteria_4095.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1566_bacteria_4099.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1567_bacteria_4100.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1567_vi

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1614_bacteria_4248.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1615_bacteria_4249.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1616_bacteria_4251.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1617_bacteria_4254.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1617_bacteria_4255.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1617_bacteria_4256.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1618_bacteria_4258.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1619_bacteria_4261.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1619_bacteria_4262.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1619_bacteria_4266.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1619_bacteria_4267.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1619

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1684_bacteria_4461.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1684_bacteria_4462.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1684_bacteria_4463.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1685_bacteria_4465.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1686_bacteria_4466.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1687_bacteria_4468.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1689_bacteria_4472.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1689_bacteria_4473.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1689_bacteria_4474.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1690_bacteria_4475.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1691_bacteria_4479.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1691

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1817_bacteria_4675.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1818_bacteria_4676.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1819_bacteria_4677.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1823_bacteria_4682.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1830_bacteria_4693.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1835_bacteria_4699.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1838_bacteria_4703.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1839_bacteria_4705.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1841_bacteria_4708.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1843_bacteria_4710.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1847_bacteria_4716.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person1848

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person20_bacteria_67.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person20_bacteria_69.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person20_bacteria_70.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person21_bacteria_72.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person21_bacteria_73.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person22_bacteria_74.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person22_bacteria_76.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person22_bacteria_77.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person23_bacteria_100.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person23_bacteria_101.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person23_bacteria_102.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person23_bacteria_103.jpeg
D:\Python_ML_Math_2021\p

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person263_bacteria_1227.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person263_virus_546.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1228.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1229.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1230.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1231.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1232.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1233.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_bacteria_1234.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person264_virus_547.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person265_bacteria_1235.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person265_bacteria_1236.jpeg


D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person289_virus_593.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person28_bacteria_139.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person28_bacteria_141.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person28_bacteria_142.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person28_bacteria_143.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person290_bacteria_1372.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person290_virus_594.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person291_bacteria_1374.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person291_bacteria_1376.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person291_bacteria_1377.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person291_virus_596.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person292_bacteria_1378.jpeg
D:\Python_ML

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person311_bacteria_1452.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person311_bacteria_1453.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person311_virus_634.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person312_bacteria_1454.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person312_bacteria_1455.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person312_bacteria_1456.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person312_virus_635.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person313_bacteria_1457.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person313_bacteria_1458.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person313_bacteria_1459.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person313_bacteria_1460.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person313_virus_637.jpeg
D:\P

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person332_virus_685.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person333_bacteria_1539.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person333_bacteria_1540.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person333_virus_688.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person334_bacteria_1541.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person334_bacteria_1542.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person334_bacteria_1544.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person334_bacteria_1545.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person334_virus_689.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person335_virus_690.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person336_bacteria_1548.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person336_bacteria_1549.jpeg
D:\Pytho

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_bacteria_1642.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_bacteria_1643.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_bacteria_1644.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_bacteria_1645.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_bacteria_1646.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person359_virus_738.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person35_bacteria_178.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person35_bacteria_180.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person35_bacteria_181.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person360_bacteria_1647.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person360_virus_739.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person361_bacteria_1651.jpeg
D:\Pyt

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_bacteria_1750.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_bacteria_1751.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_bacteria_1752.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_bacteria_1753.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_bacteria_1754.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person383_virus_767.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person384_bacteria_1755.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person384_virus_769.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person385_bacteria_1765.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person385_bacteria_1766.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person385_virus_770.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person386_virus_771.jpeg
D:\Pytho

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person413_bacteria_1833.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person413_bacteria_1834.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person413_virus_844.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person414_bacteria_1835.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person414_virus_845.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person415_bacteria_1837.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person415_bacteria_1838.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person415_bacteria_1839.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person415_virus_847.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person416_bacteria_1840.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person416_virus_849.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person417_bacteria_1841.jpeg
D:\Pytho

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1904.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1905.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1907.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1910.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1911.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1912.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1914.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1915.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1916.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1917.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_bacteria_1918.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person441_virus_894.j

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person465_bacteria_1979.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person465_bacteria_1980.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person465_bacteria_1981.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person465_bacteria_1982.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person465_virus_957.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person466_bacteria_1983.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person466_bacteria_1984.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person466_bacteria_1986.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person466_bacteria_1987.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person466_virus_960.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person467_bacteria_1988.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person467_bacteria_1989.jpeg


D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person490_bacteria_2068.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person490_bacteria_2069.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person490_bacteria_2070.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person490_virus_996.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2071.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2073.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2075.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2080.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2081.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_bacteria_2082.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person491_virus_997.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person492_bacteria_2083.jpeg


D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person515_bacteria_2189.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person515_bacteria_2190.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person515_virus_1032.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person516_bacteria_2191.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person516_bacteria_2192.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person516_virus_1033.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person517_bacteria_2196.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person517_virus_1034.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person517_virus_1035.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person518_bacteria_2197.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person518_bacteria_2198.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person518_bacteria_2199.jpeg
D:\P

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person544_virus_1075.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person544_virus_1076.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person544_virus_1078.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person544_virus_1079.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person544_virus_1080.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person545_bacteria_2287.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person545_bacteria_2288.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person545_bacteria_2289.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person545_bacteria_2290.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person545_virus_1081.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person546_virus_1085.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person547_bacteria_2292.jpeg
D:\Python_ML_

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person572_bacteria_2368.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person573_bacteria_2369.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person573_virus_1116.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person574_bacteria_2370.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person574_bacteria_2371.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person574_bacteria_2372.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person574_bacteria_2373.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person574_virus_1118.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person575_bacteria_2374.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person575_virus_1119.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person576_bacteria_2375.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person576_bacteria_2376.jpeg
D

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_279.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_280.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_281.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_282.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_283.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person59_bacteria_284.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person5_bacteria_15.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person5_bacteria_16.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person5_bacteria_17.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person5_bacteria_19.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person600_bacteria_2456.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person600_bacteria_2457.jpeg
D:\Python_ML_Math_20

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person62_bacteria_303.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_bacteria_2512.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_bacteria_2513.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_bacteria_2514.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_bacteria_2515.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_bacteria_2516.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person630_virus_1209.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person632_bacteria_2520.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person632_bacteria_2521.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person632_virus_1211.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person633_bacteria_2522.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person633_virus_1213.jpeg
D:\

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person683_bacteria_2578.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person684_bacteria_2580.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person684_virus_1275.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person685_bacteria_2581.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person687_bacteria_2583.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person688_bacteria_2584.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person688_virus_1281.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person688_virus_1282.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person689_bacteria_2585.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person689_bacteria_2586.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person68_bacteria_335.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person68_bacteria_336.jpeg
D:\Py

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person745_bacteria_2648.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person745_virus_1368.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person746_bacteria_2649.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person746_virus_1369.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person747_bacteria_2650.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person747_virus_1370.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person747_virus_1372.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person748_virus_1373.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person749_bacteria_2652.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person749_virus_1374.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person74_bacteria_361.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person74_bacteria_362.jpeg
D:\Python_ML_M

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person807_virus_1441.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person808_bacteria_2716.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person808_virus_1442.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person809_bacteria_2717.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person809_bacteria_2718.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person80_virus_150.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person810_bacteria_2719.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person810_virus_1445.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person810_virus_1446.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person811_bacteria_2721.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person811_virus_1447.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person813_bacteria_2723.jpeg
D:\Python_ML

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person878_virus_1526.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person87_virus_160.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person880_bacteria_2804.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person880_virus_1529.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person881_bacteria_2805.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person881_virus_1531.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person882_bacteria_2806.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person883_bacteria_2807.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person883_virus_1533.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person884_bacteria_2808.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person884_virus_1534.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person885_bacteria_2809.jpeg
D:\Python_ML

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person940_virus_1609.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person941_virus_1610.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person942_bacteria_2867.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person942_virus_1611.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person943_bacteria_2868.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person944_bacteria_2869.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person945_bacteria_2870.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person945_virus_1616.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person946_bacteria_2871.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person947_bacteria_2872.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person947_virus_1618.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person949_bacteria_2874.jpeg
D:\Pyth

D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person995_bacteria_2923.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person995_virus_1676.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person996_bacteria_2924.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person996_virus_1677.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person997_bacteria_2926.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person997_virus_1678.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person998_bacteria_2927.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person998_bacteria_2928.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person99_virus_183.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person9_bacteria_38.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person9_bacteria_39.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\COVID19\person9_bacteria_40.jpeg
D:\Python_ML_Math_

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0275-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0276-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0277-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0278-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0279-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0280-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0282-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0283-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0285-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0286-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0288-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0289-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0290-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0291-00

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0417-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0419-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0420-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0421-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0423-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0424-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0425-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0427-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0428-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0429-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0429-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0429-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0430-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0516-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0517-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0517-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0519-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0519-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0519-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0520-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0521-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0522-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0523-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0523-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0523-0001-0003.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0523-0001.jpeg
D:\Python_ML_Math_2021\project\lun

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0615-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0616-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0617-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0618-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0618-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0618-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0619-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0620-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0620-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0620-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0621-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0622-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0622-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lun

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0715-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0716-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0717-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0718-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0719-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0721-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0722-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0724-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0727-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0728-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0729-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0730-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0732-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\IM-0733-00

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0482-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0485-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0486-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0487-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0488-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0489-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0490-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0491-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0493-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0496-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0497-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0499-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0636-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0637-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0640-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0641-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0642-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0643-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0645-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0647-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0648-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0649-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0650-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0651-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0829-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0830-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0831-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0832-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0832-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0832-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0833-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0834-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0836-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0837-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0838-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0839-0001.jpeg
D:\Python_ML_Math_2021\project

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0957-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0959-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0960-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0961-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0962-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0965-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0966-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0967-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0969-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0970-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0971-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-0971-0001-0002.jpeg
D:\Python_ML_Math_2021\project

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1102-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1102-0001-0002.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1102-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1103-0001-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1104-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1105-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1106-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1108-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1109-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1110-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1111-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1112-0001.jpeg
D:\Python_ML_Math_2021\pr

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1226-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1227-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1228-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1231-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1232-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1234-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1236-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1237-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1240-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1241-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1242-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1243-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray

D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1349-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1350-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1351-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1356-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1357-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1360-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1362-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1365-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1371-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1376-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1379-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\train\NORMAL\NORMAL2-IM-1385-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray

<_io.BufferedWriter name='train.pickle'>

In [39]:
features = []
labels = []
pick_in = open('train.pickle', 'rb')
data = pickle.load(pick_in)
pick_in.close()
for feature, label in data:
    features.append(feature)
    labels.append(label)





Նույն գործողությունները կատարում եմ Test data-յի համար

In [18]:
dir ='D:\\Python_ML_Math_2021\\project\\lung_xray\\test' 
data2 = []

In [47]:
for category in categories:
    path = os.path.join(dir,category)
    label =  categories.index(category)
    for image in os.listdir(path):
        imgpath = os.path.join(path,image)
        print(imgpath)
        test_img = cv2.imread(imgpath,0)
        test_img=cv2.resize(test_img,shape)
        cv2.imshow('image', test_img)
        test_img = np.array(test_img).flatten()
        data2.append([test_img,label])


D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_475.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_477.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_478.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_479.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_480.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_481.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person100_bacteria_482.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person101_bacteria_483.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person101_bacteria_484.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person101_bacteria_485.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person101_bacteria_486.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person102_bacteria_487.jpeg
D:\Python_ML_Mat

D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person135_bacteria_647.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person136_bacteria_648.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person136_bacteria_649.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person136_bacteria_650.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person136_bacteria_652.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person136_bacteria_654.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person137_bacteria_655.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person138_bacteria_657.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person138_bacteria_658.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person138_bacteria_659.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person139_bacteria_661.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person139_bacteria_662.jpeg
D:\Python_ML_Mat

D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1657_virus_2864.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1659_virus_2867.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1660_virus_2869.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1661_virus_2872.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1661_virus_2873.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1662_virus_2875.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1663_virus_2876.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1664_virus_2877.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1665_virus_2878.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1667_virus_2881.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1668_virus_2882.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person1669_virus_2884.jpeg
D:\Python_ML_Math_2021\proje

D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person72_virus_133.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person74_virus_135.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person75_virus_136.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person76_virus_138.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person77_virus_139.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_378.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_380.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_381.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_382.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_384.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_385.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\COVID19\person78_bacteria_386.jpeg
D:\Python_ML_Math_2021\project\lung_xray\te

D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0049-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0050-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0059-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0061-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0063-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0065-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0067-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0069-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0070-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0071-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0073-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0075-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0077-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\IM-0079-0001.jpeg
D:\Pyt

D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0272-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0273-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0274-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0275-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0276-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0277-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0278-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0279-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0280-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0281-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0282-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL\NORMAL2-IM-0283-0001.jpeg
D:\Python_ML_Math_2021\project\lung_xray\test\NORMAL

In [48]:
pick_in = open('test.pickle','wb')
pickle.dump(data2,pick_in)
pick_in.close()
pick_in


    

<_io.BufferedWriter name='test.pickle'>

In [49]:
pick_in = open('test.pickle', 'rb')
data2 = pickle.load(pick_in)
pick_in.close()
features_test = []
labels_test = []
for feature, label in data2:
    features_test.append(feature)
    labels_test.append(label)

In [50]:
data2

[[array([20, 21, 16, ...,  0,  0,  0], dtype=uint8), 0],
 [array([54, 42, 39, ..., 23, 20, 82], dtype=uint8), 0],
 [array([184, 172, 175, ..., 121,  82, 102], dtype=uint8), 0],
 [array([36, 39, 41, ..., 10, 10, 10], dtype=uint8), 0],
 [array([111, 102,  96, ...,  28,  25,  26], dtype=uint8), 0],
 [array([59, 36, 35, ..., 10, 11, 11], dtype=uint8), 0],
 [array([135, 119, 115, ...,  19,  19,  19], dtype=uint8), 0],
 [array([73, 72, 70, ..., 14, 20, 12], dtype=uint8), 0],
 [array([ 70,  71,  71, ...,  20,  77, 213], dtype=uint8), 0],
 [array([61, 64, 60, ...,  5,  5,  5], dtype=uint8), 0],
 [array([34, 38, 41, ..., 14, 16, 17], dtype=uint8), 0],
 [array([38, 41, 41, ..., 20, 20, 20], dtype=uint8), 0],
 [array([37, 40, 41, ..., 26, 24, 23], dtype=uint8), 0],
 [array([42, 44, 44, ..., 31, 49, 61], dtype=uint8), 0],
 [array([0, 0, 1, ..., 0, 0, 0], dtype=uint8), 0],
 [array([170, 170,  70, ...,  27,  25,  28], dtype=uint8), 0],
 [array([45, 39, 39, ..., 21, 19, 18], dtype=uint8), 0],
 [array

In [51]:
xtrain, xtest, ytrain, ytest = features, features_test, labels, labels_test
C=3
d=3

In [52]:
features_test

[array([20, 21, 16, ...,  0,  0,  0], dtype=uint8),
 array([54, 42, 39, ..., 23, 20, 82], dtype=uint8),
 array([184, 172, 175, ..., 121,  82, 102], dtype=uint8),
 array([36, 39, 41, ..., 10, 10, 10], dtype=uint8),
 array([111, 102,  96, ...,  28,  25,  26], dtype=uint8),
 array([59, 36, 35, ..., 10, 11, 11], dtype=uint8),
 array([135, 119, 115, ...,  19,  19,  19], dtype=uint8),
 array([73, 72, 70, ..., 14, 20, 12], dtype=uint8),
 array([ 70,  71,  71, ...,  20,  77, 213], dtype=uint8),
 array([61, 64, 60, ...,  5,  5,  5], dtype=uint8),
 array([34, 38, 41, ..., 14, 16, 17], dtype=uint8),
 array([38, 41, 41, ..., 20, 20, 20], dtype=uint8),
 array([37, 40, 41, ..., 26, 24, 23], dtype=uint8),
 array([42, 44, 44, ..., 31, 49, 61], dtype=uint8),
 array([0, 0, 1, ..., 0, 0, 0], dtype=uint8),
 array([170, 170,  70, ...,  27,  25,  28], dtype=uint8),
 array([45, 39, 39, ..., 21, 19, 18], dtype=uint8),
 array([217, 210, 190, ...,  23,  24,  24], dtype=uint8),
 array([209, 208, 210, ...,  55,  

In [53]:
model = SVC(C=C, kernel='linear', gamma='auto', degree=d, verbose=True).fit(xtrain, ytrain)


[LibSVM]

In [54]:
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

accuracy = model.score(xtest, ytest)
print("accuracy", C, " ", d, ' ', accuracy * 100, '%')

accuracy 3   3   75.32051282051282 %


In [55]:
ytest

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [56]:
model = pickle.load(open(filename, 'rb'))
result = model.score(xtest,ytest)
print(result)


0.7532051282051282


In [27]:
#img=cv2.imread('D:\\Python_ML_Math_2021\\project\\lung_xray\\test\\COVID19\\COVID19(460).jpg',0)

In [66]:
img=cv2.imread('../lung_xray/test/COVID19/person100_bacteria_475.jpeg',0)
print(img)

[[ 1 24 18 ... 81 88 88]
 [ 1 24 18 ... 86 86 86]
 [ 0 24 17 ... 91 85 85]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [63]:
!dir

 Volume in drive D is Disk
 Volume Serial Number is 7C61-EB7B

 Directory of D:\Python_ML_Math_2021\project\Covid_Classification

28-Apr-21  12:02 PM    <DIR>          .
28-Apr-21  12:02 PM    <DIR>          ..
28-Apr-21  10:32 AM    <DIR>          .ipynb_checkpoints
28-Apr-21  12:02 PM           685,115 Covid_class_X-RAYS.ipynb
28-Apr-21  11:58 AM       406,864,132 finalized_model.sav
28-Apr-21  10:29 AM                19 README.md
28-Apr-21  11:52 AM        40,926,409 test.pickle
28-Apr-21  11:01 AM       342,101,923 train.pickle
               5 File(s)    790,577,598 bytes
               3 Dir(s)  295,700,197,376 bytes free


Հետևյալ ծրագրային կտորի միջոցով ստուգվում է նոր data-ն և նկարի վրա ավելանում է կանխատեսման արդյունքը ՛N E G A T I V E՛ և 'P O S I T I V E' բառերի տեսքով

In [86]:
img=cv2.imread('../lung_xray/test/COVID19/person100_bacteria_478.jpeg',0) # փորձարկելու համար կարելի է թոքերի X-rays-ի նկար (տալով ճիշտ հղումը) քաշել ինտերնետից և ստուգել մոդելը
tstimg=cv2.resize(img,shape)
tstimg = np.array(tstimg).flatten()
tstimg=tstimg.reshape(1,-1)
prediction = model.predict(tstimg)
cv2.resize(img,(800,600))
if prediction:
    cv2.putText(img,'N E G A T I V E',(100,100),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),3)
else:
    cv2.putText(img,'P O S I T I V E',(300,300),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),3)

cv2.imshow('hey',cv2.resize(img,(500,500)))
cv2.waitKey(-1)

-1